name: transformer-metarl-walker
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py37h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=heb0550a_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py37hff7bd54_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1i=h27cfd23_0
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.2.4=py37h06a4308_0
  - python=3.7.9=h7579374_0
  - pytorch=1.7.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - alabaster==0.7.12
    - apipkg==1.5
    - appdirs==1.4.4
    - astroid==2.4.2
    - babel==2.9.0
    - cfgv==3.2.0
    - commonmark==0.9.1
    - coverage==5.3
    - distlib==0.3.1
    - dm-control==0.0.300771433
    - dm-env==1.3
    - docutils==0.16
    - execnet==1.7.1
    - flake8==3.8.4
    - flake8-docstrings==1.5.0
    - flake8-import-order==0.18.1
    - flake8-polyfill==1.0.2
    - gym[mujoco]==0.9.1
    - mujoco-py==0.5.7
    - identify==1.5.10
    - imagesize==1.2.0
    - iniconfig==1.1.1
    - isort==5.6.4
    - jinja2==2.11.2
    - lazy-object-proxy==1.4.3
    - lxml==4.6.1
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - nodeenv==1.5.0
    - packaging==20.4
    - pep8-naming==0.7.0
    - pluggy==0.13.1
    - pre-commit==2.9.2
    - prettytable==2.0.0
    - py==1.9.0
    - pycodestyle==2.6.0
    - pydocstyle==5.1.1
    - pyflakes==2.2.0
    - pygments==2.7.2
    - pylint==2.6.0
    - pyopengl==3.1.5
    - pytest==6.1.2
    - pytest-cov==2.10.1
    - pytest-forked==1.3.0
    - pytest-timeout==1.4.2
    - pytest-xdist==2.1.0
    - pytz==2020.4
    - recommonmark==0.6.0
    - snowballstemmer==2.0.0
    - sphinx==3.3.1
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - toml==0.10.2
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - typed-ast==1.4.1
    - virtualenv==20.2.1
    - wcwidth==0.2.5
    - yapf==0.28.0
prefix: /data/anaconda3/envs/transformer-metarl-walker

